language: node_js
sudo: false
node_js:
  - 4
install:
  - npm install
script:
  - npm test
after_success:
- >-
  test $TRAVIS_TAG &&
  npm install bower -g &&
  node_modules/.bin/psc-publish > .pursuit.json &&
  curl -X POST http://pursuit.purescript.org/packages \
    -d @.pursuit.json \
    -H 'Accept: application/json' \
    -H "Authorization: token ${GITHUB_TOKEN}"
